FROM index.alauda.cn/alaudaorg/qaimages:volumetest
LABEL Version="1.1.9071111903372222"
RUN chmod +x /run.sh                                                                                                                                                                                                                  
CMD ["/a.sh"] 